"""Add envelope encryption fields

Revision ID: 27651a85638f
Revises: afb7159da886
Create Date: 2026-01-09 10:35:54.080329+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27651a85638f'
down_revision: Union[str, None] = 'afb7159da886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret_versions', sa.Column('encrypted_dek', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret_versions', 'encrypted_dek')
    # ### end Alembic commands ###